# Generated by Django 3.1.4 on 2021-01-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Option',
        ),
    ]
